---
# vars file for coreos_kubernetes
file_paths:
  /etc/dnf/modules.d/:
    - file_name: cri-o.module
      file_contents: |
        [cri-o]
        name=cri-o
        stream=1.17
        profiles=
        state=enabled
  /etc/modules-load.d/:
    - file_name: overlay.conf
      file_contents: overlay
    - file_name: br_netfilter.conf
      file_contents: br_netfilter
  /etc/selinux/:
    - file_name: config
      file_contents: SELINUX=disabled
sysctl_params:
  90-sysrq.conf:
    - param_name: kernel.sysrq
      param_value: 0
  100-kubernetes.conf:
    - param_name: net.bridge.bridge-nf-call-iptables
      param_value: 1 
    - param_name: net.bridge.bridge-nf-call-ip6tables
      param_value: 1
    - param_name: net.ipv4.ip_forward
      param_value: 1
    - param_name: net.ipv6.conf.eth0.forwarding
      param_value: 1
    - param_name: net.ipv6.conf.all.forwarding
      param_value: 1
fedora_mod_repos:
  /etc/yum.repos.d/:
    - repo_file: fedora-modular.repo 
      repo_section: fedora-modular
      repo_option: enabled
      repo_value: 1
    - repo_file: fedora-updates-modular.repo
      repo_section: updates-modular
      repo_option: enabled
      repo_value: 1
kubernetes_repos:
  Kubernetes:
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey_path: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: 1
    repo_gpgcheck: 1
    enabled: 1
